spring.application.name=AuditService

spring.datasource.url=jdbc:postgresql://localhost:5432/audit_tenants_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration/tenant

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:29092
spring.kafka.topic=audit-topic
spring.kafka.consumer-group-prefix=
spring.kafka.partitions=
spring.kafka.max-partition-fetch-bytes=1048576
spring.kafka.fetch-max-bytes=1048576

